version: "3.1"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dummy
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
